site_name: 'Axe: Cloud Hatchet'
site_author: 'Hugh Mooney'
pages:
- 'Getting Started': 'index.md'
- 'For Users':
    - 'Using the AXE tools': 'cmd/general.md'
    - 'AXE Tool Commands':
        - 'axe-auth-report': 'cmd/axe-auth-report.md'
        - 'axe-auth-setup': 'cmd/axe-auth-setup.md'
        - 'axe-auth-token-create': 'cmd/axe-auth-token-create.md'
        - 'axe-cloud-template-create': 'cmd/axe-cloud-template-create.md'
        - 'axe-env-list': 'cmd/axe-env-list.md'
        - 'axe-image-list': 'cmd/axe-image-list.md'
        - 'axe-instance-list': 'cmd/axe-instance-list.md'
        - 'axe-instance-create': 'cmd/axe-instance-create.md'
        - 'axe-ssh': 'cmd/axe-ssh.md'
        - 'axe-scp': 'cmd/axe-scp.md'
    - 'AXE Identity Management': 'axe_id.md'
    - 'AXE Stack Management': 'axe_stack.md'
- 'For Developers/Contributors':
    - 'Developer Notes': 'dev/README.md'
    - 'LIB: logger': 'dev/lib/axeutils/logger.md'
    - 'LIB: config': 'dev/lib/axeutils/config.md'
repo_url: 'https://bitbucket.org/kxseven/axe'
theme_dir: 'themes/version1_web'
